spring.application.name=Hospital-Management


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hospital;encrypt=false
spring.datasource.username=root
spring.datasource.password=root


spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

jwt.securityKey = wopiasdvcn1239asdhaow83413hva092ejg